# Form implementation generated from reading ui file 'InvoiceDetection.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets
from setting import INVOICE_FORMAT


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 581)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnLoad = QtWidgets.QPushButton(self.centralwidget)
        self.btnLoad.setGeometry(QtCore.QRect(670, 20, 111, 32))
        self.btnLoad.setObjectName("btnLoad")
        self.btnSave = QtWidgets.QPushButton(self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(670, 57, 111, 32))
        self.btnSave.setObjectName("btnSave")
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(260, 97, 221, 32))
        self.btnStart.setObjectName("btnStart")
        self.labelFormat = QtWidgets.QLabel(self.centralwidget)
        self.labelFormat.setGeometry(QtCore.QRect(30, 100, 60, 21))
        self.labelFormat.setObjectName("labelFormat")
        self.labelConsole = QtWidgets.QLabel(self.centralwidget)
        self.labelConsole.setGeometry(QtCore.QRect(490, 100, 280, 21))
        self.labelConsole.setObjectName("labelConsole")
        self.comboBoxFormat = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxFormat.setGeometry(QtCore.QRect(90, 100, 151, 26))
        self.comboBoxFormat.setObjectName("comboBoxFormat")
        for item in INVOICE_FORMAT:
            self.comboBoxFormat.addItem(item)
        self.lineEditLoad = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditLoad.setGeometry(QtCore.QRect(90, 25, 571, 21))
        self.lineEditLoad.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.lineEditLoad.setObjectName("lineEditLoad")
        self.lineEditSave = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditSave.setGeometry(QtCore.QRect(90, 62, 571, 21))
        self.lineEditSave.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.lineEditSave.setObjectName("lineEditSave")
        self.labelPath = QtWidgets.QLabel(self.centralwidget)
        self.labelPath.setGeometry(QtCore.QRect(30, 20, 60, 31))
        self.labelPath.setObjectName("labelPath")
        self.labelSave = QtWidgets.QLabel(self.centralwidget)
        self.labelSave.setGeometry(QtCore.QRect(30, 57, 60, 31))
        self.labelSave.setObjectName("labelSave")

        self.canvas = QtWidgets.QGraphicsView(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(61, 140, 678, 409))
        self.canvas.setObjectName("canvas")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Image Detection"))
        self.btnLoad.setText(_translate("MainWindow", "Select Folder"))
        self.btnSave.setText(_translate("MainWindow", "Select Folder"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.labelFormat.setText(_translate("MainWindow", "Format"))
        self.labelConsole.setText(_translate("MainWindow", "Please fill in data"))
        self.labelPath.setText(_translate("MainWindow", "Open"))
        self.labelSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
